Update for 1.18.2
TerraformersMC/Dossier pull request #3
Opened 2022-03-31 22:57 UTC by Jade-TheCat

Noticed Campanion doesn't work on 1.18.2, so I updated Dossier and Campanion. More testing may be necessary, but I believe that the tag changes should be all that is needed here. That said, since this is a breaking change as it uses different classes in the tag bits, so I recommend (and have done in the build.gradle for testing) a version bump to 0.6.0.

2022-03-31 22:58 UTC, Jade-TheCat commented
PR for Campanion: https://github.com/TerraformersMC/Campanion/pull/163

2022-04-11 08:41 UTC, jhbuchanan45 requested changes
@Jade-TheCat everything looks fine here, assuming it works with Campanion and you can get the VSCode files removed, then I'll go annoy someone else who can actually merge it. 

I'm not sure if I'd call these changes breaking, it looks like just a change in the minecraft mappings from Tag to TagKey, but we'll see what NeusFear thinks (or whoever does the merge)

2022-04-11 08:41 UTC, jhbuchanan45 commented on .vscode/launch.json
> +{
Looks like these files in `.vscode/` slipped through the cracks, use `git rm -r --cached <folder>` to remove them and commit again. I've had this issue before, I think it has to do with git only ignoring adding new files, not ones that have already been added to a commit.

2022-04-20 16:38 UTC, NeusFear approved these changes
Agreed once you can remove the vscode files this should be mergable

2022-05-24 00:49 UTC, Jade-TheCat commented
Closing since a 1.18.2 update has already gone through! Thank y'all!

2022-05-24 00:49 UTC, closed without merging